### ISSUE TITLE
unhandled error event

### ISSUE THREAD

**Issue by simon387** [maltempi/telnet-mock#1]
Hi, i got this error when trying to use it with a JSch client

```
/home/user/>
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at TelnetServerProtocolStream._sendToConsumer (/telnet-mock/node_modules/sol-telnet/index.js:86:28)
    at TelnetServerProtocolStream.sendCommand /telnet-mock/node_modules/sol-telnet/index.js:119:12)
    at TelnetServerProtocolStream._handleCommand (/telnet-mock/node_modules/sol-telnet/index.js:132:22)
    at TelnetServerProtocolStream._write (/telnet-mock/node_modules/sol-telnet/index.js:298:19)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by maltempi** [comment]
Hey @simon387 
Sorry, I'm not using this project for a long time, I'd need to revisit it. Any luck with this?

Anyways, post the command you send to the server and your .json. Then if I have some free time I can take a look.

Also, feel free to open a pull request in case you solved this.
